apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    name: analytics
spec:
  replicas: 3
  selector:
    matchLabels:
      service: analytics
  template:
    metadata:
      labels:
        service: analytics
    spec:
      containers:
      - name: analytics
        image: isjustintime/cd12355-admin-api:0.1.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5151
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5151
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          value: app-db
      restartPolicy: Always
